sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t besteban/java-jdk-arm .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG="jdk-8u111-b14"
    docker tag besteban/java-jdk-arm besteban/java-jdk-arm:$TAG
    docker push besteban/java-jdk-arm:$TAG
    docker push besteban/java-jdk-arm
  fi
